security:
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username

    role_hierarchy:
        ROLE_USER:       ROLE_USER

    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager

            logout:       true
            anonymous: ~
            oauth:
              resource_owners:
                  facebook: "/connect/login-facebook"
                  google: "/connect/login-google"
              login_path:        fos_user_security_login
              use_forward:       false
              failure_path:      fos_user_security_login

              oauth_user_provider:
                    service: hwi_oauth.user.provider.fosub_bridge
    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }