version: "2"

services:
  nginx.symfony:
    container_name: nginx.symfony
    image: nginx:1.13.10
    volumes:
      - ../:/code
      - ./nginx/site.conf:/etc/nginx/conf.d/site.conf
    ports:
      - 127.0.0.1:80:80

  php.symfony:
    container_name: php.symfony
    image: php.symfony
    environment:
      - APP_ENV=prod
      - APP_SECRET=pikusas
      - DATABASE_URL=mysql://root:egliote@mysql.symfony:3306/mums_pakeliui
    volumes:
      - ../:/code

  mysql.symfony:
    container_name: mysql.symfony
    image: mysql:5.7.21
    environment:
      - MYSQL_ROOT_PASSWORD=egliote
    volumes:
      - ./mysql-data/:/var/lib/mysql

  frontend.symfony:
    container_name: frontend.symfony
    image: frontend.symfony
    volumes:
      - ../:/code
